spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://117.50.22.78:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
  jpa:
    database: MySQL
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true


time:
  interval: 60000
request:
  limit: 4
  
